export const data = [
	{
		ID: 1,
		FirstName: 'John Doe',
		Username: 'johndoe',
		lastMessage: 'Hello, how are you?',
		lastMessageTime: '10:30 AM',
		Avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
	},
	{
		ID: 2,
		FirstName: 'Jane Smith',
		Username: 'janesmith',
		lastMessage: 'Are you coming to the party?',
		lastMessageTime: '9:15 AM',
		Avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
	},
	{
		ID: 3,
		FirstName: 'Bob Johnson',
		Username: 'bobjohnson',
		lastMessage: 'Can you send me the report?',
		lastMessageTime: 'Yesterday',
		Avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
	},
	{
		ID: 4,
		FirstName: 'Alice Williams',
		Username: 'alicewilliams',
		lastMessage: "Let's catch up soon!",
		lastMessageTime: '2 days ago',
		Avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
	},
	{
		ID: 5,
		FirstName: 'Charlie Brown',
		Username: 'charliebrown',
		lastMessage: 'Thanks for your help!',
		lastMessageTime: '1 week ago',
		Avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
	},
	{
		ID: 6,
		FirstName: 'Diana Miller',
		Username: 'dianamiller',
		lastMessage: 'See you at the meeting!',
		lastMessageTime: '3 days ago',
		Avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
	},
]
